# -*- coding: utf-8 -*-
"""延畢生.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MkwouOHP5l7Ci5IgR3g8aZxaIIxdE1j_
"""

import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

"""## New Tips: 
1. NaN to zero is fillna(0)
2.
"""

df1061=pd.read_excel("abc.xlsx", encoding="big5")
df1062=pd.read_excel("def.xlsx", encoding ="big5")

df1061=df1061[~df1061["院 系 組 別"].str.contains("學院", na=False)]
df1062=df1062[~df1062["院 系 組 別"].str.contains("學院", na=False)]

df1061=df1061.fillna(0) 
df1062=df1062.fillna(0)

df1061.columns=["Department", "Code", "Total Amount", "Delay Male", "Delay Female"]
df1061=df1061.iloc[2:,:]
df1062.columns=["Department", "Code", "Total Amount", "Delay Male", "Delay Female"]
df1062=df1062.iloc[2:,:]

DelayMale1061 = df1061.iloc[:,3]
DelayFemale1061 = df1061.iloc[:,4]
DelayMale1062 = df1062.iloc[:,3]
DelayFemale1062 = df1062.iloc[:,4]

list(DelayFemale1061)
list(DelayMale1061)
TotalDelay1061=[x+y for x,y in zip(DelayMale1061, DelayFemale1061)]
list(DelayFemale1062)
list(DelayMale1062)
TotalDelay1062=[x+y for x,y in zip(DelayMale1062, DelayFemale1062)]

df1061["Total Delay"]=TotalDelay1061
df1062["Total Delay"]=TotalDelay1062

DelayMale1061 = df1061.iloc[:,3]
DelayFemale1061 = df1061.iloc[:,4]
DelayMale1062 = df1062.iloc[:,3]
DelayFemale1062 = df1062.iloc[:,4]


list(DelayFemale1061)
list(DelayMale1061)
TotalDelay1061=[x+y for x,y in zip(DelayMale1061, DelayFemale1061)]
list(DelayFemale1062)
list(DelayMale1062)
TotalDelay1062=[x+y for x,y in zip(DelayMale1062, DelayFemale1062)]

df1061["Total Delay"]=TotalDelay1061
df1062["Total Delay"]=TotalDelay1062

TotalDelay1061=list(df1061["Total Delay"])
TotalAmount1061=list(df1061["Total Amount"])
Final1061=[x/y for x,y in zip(TotalDelay1061,TotalAmount1061)]
df1061["Percent"]=Final1061
Department1061=df1061[df1061["Percent"]==df1061["Percent"].max()].iloc[0,0]
TotalDelay1062=list(df1062["Total Delay"])
TotalAmount1062=list(df1062["Total Amount"])
Final1062=[x/y for x,y in zip(TotalDelay1062,TotalAmount1062)]
df1062["Percent"]=Final1062
Department1062=df1062[df1062["Percent"]==df1062["Percent"].max()].iloc[0,0]

print(f"106年延畢業率最高的系：\n上學期：{Department1061}\n下學期：{Department1062}")